services:
  yggdrasil:
    image: ghcr.io/wgos/yggdrasil-docker:latest
    volumes:
      - ./conf:/etc/yggdrasil
    ports:
      - 1514:1514
      - 1515:1515
      - 1515:1515/udp
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    restart: always