name: Build Docker

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - { yggdrasil: '0.5.12', latest: true }

    steps:
      - name: Lowercase repo name
        run: |
          echo "REPO_NAME_LC=${REPO_NAME,,}" >>${GITHUB_ENV}
        env:
          REPO_NAME: '${{ github.repository }}'
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME_LC }}:${{ matrix.yggdrasil }}
            ${{ matrix.latest && format('ghcr.io/{0}:latest', env.REPO_NAME_LC) }}
          build-args: |
            YGG_VER=${{ matrix.yggdrasil }}
          platforms: |
            linux/amd64
            linux/arm64
